Feature/consuming multiple event types (#7)
* refactor project

* add handler

* add trusted packages

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -6,7 +6,7 @@ on:
   push:
     branches: [ "main", "master", "feature/**", "release/**" ]
   pull_request:
-    branches: [ "main", "master" ]  
+    branches: [ "main", "master" ]
   schedule:
     - cron: '5 2 * * *' # daily at 2:05
 jobs:
@@ -25,6 +25,7 @@ jobs:
       MVN_VERSION: ${{ steps.set_version.outputs.MVN_VERSION }}
       ARTIFACT_ID: ${{ steps.set_version.outputs.ARTIFACT_ID }}
       GROUP_ID: ${{ steps.set_version.outputs.GROUP_ID }}
+      ORGANIZATION: ${{ steps.set_version.outputs.ORGANIZATION }}
 
     steps:
       - uses: actions/checkout@v4
@@ -59,12 +60,13 @@ jobs:
           echo "### ALLMYVARS: $ALLMYVARS"
           echo "### ALLMYOUTPUT: $ALLMYOUTPUT"
           echo ":sunflower: Cleaned Branch Name: ${{ steps.set_version.outputs.BRANCH_NAME }}" >> $GITHUB_STEP_SUMMARY
+          echo ":maple_leaf: ORGANIZATION: ${{ steps.set_version.outputs.ORGANIZATION }}" >> $GITHUB_STEP_SUMMARY
           echo ":maple_leaf: GROUP ID: ${{ steps.set_version.outputs.GROUP_ID }}" >> $GITHUB_STEP_SUMMARY
           echo ":maple_leaf: Artifact ID: ${{ steps.set_version.outputs.ARTIFACT_ID }}" >> $GITHUB_STEP_SUMMARY
           echo ":maple_leaf: Original Maven version: ${{ steps.set_version.outputs.MVN_VERSION }}" >> $GITHUB_STEP_SUMMARY
           echo ":cactus: Calculated Maven Version: ${{ steps.set_version.outputs.BRANCH_MVN_VERSION }}" >> $GITHUB_STEP_SUMMARY
-          
-
+  
+  
   build:
     runs-on: ubuntu-latest
 
@@ -81,7 +83,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-        
+
       - name: Set up java 21
         uses: actions/setup-java@v4
         with:
@@ -133,6 +135,62 @@ jobs:
           fi
           mvn -B -e deploy -s $GITHUB_WORKSPACE/settings.xml
           
+  analyze:
+    runs-on: ubuntu-latest
+    needs: [ setup ]
+        
+    permissions:
+      contents: read
+      packages: write
+      id-token: write
+      checks: write
+      pull-requests: write
+      actions: read
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0    
+          
+      - name: Set up java 21
+        uses: actions/setup-java@v4
+        with:
+          java-version: 21
+          distribution: 'temurin'
+          cache: 'maven'
+          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml.
+          settings-path: ${{ github.workspace }} # location for the settings.xml file       
+
+      - name: Run Maven Build
+        env:
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_TOKEN: ${{ github.token }}
+          BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
+          BRANCH_NAME: ${{needs.setup.outputs.BRANCH_NAME}}
+          DOCKER_USER: ${{ secrets.DOCKER_USER }}
+          DOCKER_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
+        run: |
+          set -o pipefail    # don't hide errors within pipes
+          set -o nounset     # abort on unbound variable
+          set -o errexit     # abort on nonzero exit status
+
+          # Check if required parameters are set
+          required_params=("GITHUB_ACTOR" "GITHUB_TOKEN" "BRANCH_MVN_VERSION" "BRANCH_NAME" "DOCKER_USER" "DOCKER_TOKEN")
+          for param in "${required_params[@]}"; do
+            if [ -z "${!param}" ]; then
+              echo "::error::Required parameter $param is not set"
+              exit 1
+            fi
+          done
+
+          if [[ "${BRANCH_NAME}" == "master" ||  "${BRANCH_NAME}" == "main" ]]; then
+            echo "::notice:: ### Build of Master. Version: $BRANCH_MVN_VERSION"
+          else
+            echo "::notice:: ### Build of Feature Branch ${BRANCH_NAME}. Version: $BRANCH_MVN_VERSION"
+            mvn -B versions:set -e -DnewVersion="$BRANCH_MVN_VERSION"
+          fi
+          mvn -B -e install -Dskip.start.stop.springboot=true -s $GITHUB_WORKSPACE/settings.xml	
+      
       - name: Publish Test Results
         uses: EnricoMi/publish-unit-test-result-action@v2
         if: always()
@@ -140,3 +198,52 @@ jobs:
           files: |
             ./target/surefire-reports/TEST-*.xml
             ./target/failsafe-reports/TEST-*.xml
+      
+      - name: analyze
+        env:
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_TOKEN: ${{ github.token }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
+          BRANCH_NAME: ${{needs.setup.outputs.BRANCH_NAME}}
+          DOCKER_USER: ${{ secrets.DOCKER_USER }}
+          DOCKER_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
+          ORGANIZATION: ${{needs.setup.outputs.ORGANIZATION}}
+          ARTIFACT_ID: ${{needs.setup.outputs.ARTIFACT_ID}}
+          
+        run: |
+          set -o pipefail    # don't hide errors within pipes
+          set -o nounset     # abort on unbound variable
+          set -o errexit     # abort on nonzero exit status
+          
+          # Check if required parameters are set
+          required_params=("SONAR_TOKEN")
+          for param in "${required_params[@]}"; do
+            if [ -z "${!param}" ]; then
+              echo "::error::Required parameter $param is not set"
+              exit 1
+            fi
+          done
+          
+          if [[ "${BRANCH_NAME}" == "master" ||  "${BRANCH_NAME}" == "main" ]]; then
+            mvn -B sonar:sonar \
+                  -s $GITHUB_WORKSPACE/settings.xml \
+                  -Dsonar.token=${SONAR_TOKEN} \
+                  -Dsonar.host.url=https://sonarcloud.io \
+                  -Dsonar.sourceEncoding=UTF-8 \
+                  -Dsonar.organization=${ORGANIZATION} \
+                  -Dsonar.projectKey="${ORGANIZATION}_${ARTIFACT_ID}" \
+                  -Dsonar.branch.name=master
+          else
+            mvn -B versions:set -e -DnewVersion="$BRANCH_MVN_VERSION"
+            mvn -B sonar:sonar \
+                  -s $GITHUB_WORKSPACE/settings.xml \
+                  -Dsonar.token=${SONAR_TOKEN} \
+                  -Dsonar.host.url=https://sonarcloud.io \
+                  -Dsonar.sourceEncoding=UTF-8 \
+                  -Dsonar.organization=${ORGANIZATION} \
+                  -Dsonar.projectKey="${ORGANIZATION}_${ARTIFACT_ID}" \
+                  -Dsonar.branch.name=${BRANCH_NAME} \
+                  -Dsonar.branch.target=master
+          fi 
+        
